---
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_users_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    # command: tail -f /dev/null
    # command: python manage.py runserver 0.0.0.0:${APP_PORT}
    command: uwsgi --http 0.0.0.0:${APP_PORT} --module users.wsgi:application --master --processes 4 --threads 2 --static-map /app/static=/app/static/
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}

  postgres:
    image: postgres:17
    container_name: dev_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
