---
name: SSH into Remote and Update Repository
on:
  workflow_dispatch:
    inputs:
      remote_ip:
        description: "The IP address of the remote server"
        required: true
        default: "192.168.1.1"  # Default IP address (can be overridden)
      git_version:
        description: "The Git branch or tag to check out"
        required: true
        default: "main"  # Default branch (can be overridden)

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add the private key to GitHub secrets

      - name: Run git commands in specific directories
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ github.event.inputs.remote_ip }} "
            sudo -u test_api_user git -C /home/test_api_user/app fetch &&
            sudo -u test_api_user git -C /home/test_api_user/app checkout ${{ github.event.inputs.git_version }} &&
            echo 'Checked out ${{ github.event.inputs.git_version }}' &&

            sudo systemctl restart test-api
          "
